### ISSUE TITLE
No module error

### ISSUE THREAD

**Issue by falak001** [limontec/WhatsApp-GDrive-Downloader#5]
Traceback (most recent call last):
  File "whapa/libs/whagodri.py", line 7, in <module>
    import gpsoauth
  File "/content/whapa/libs/gpsoauth/__init__.py", line 5, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'

Kindly provide solution of this error.

**Comment by limontec** [comment]
Sorry for take so long to solve this.
Fixed.
